import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { HStack, VStack, Image, Text, Button, Box } from "@chakra-ui/react";
import Link from "next/link";
import Footer from "@components/Footer";
import withTransition from "@components/withTransition";

const sampleCardCategories = [
  {
    name: "Appreciation",
    cards: [
      "/cards/appreciation_1.jpg",
      "/cards/appreciation_2.jpg",
      "/cards/appreciation_3.jpg",
      "/cards/appreciation_4.jpg",
      "/cards/appreciation_5.jpg",
      "/cards/appreciation_6.jpg",
      "/cards/appreciation_7.jpg",
    ],
  },
  {
    name: "Birthday",
    cards: [
      "/cards/birthday_1.jpg",
      "/cards/birthday_2.jpg",
      "/cards/birthday_3.jpg",
      "/cards/birthday_4.jpg",
      "/cards/birthday_5.jpg",
    ],
  },
  {
    name: "Love",
    cards: [
      "/cards/love_1.jpg",
      "/cards/love_2.jpg",
      "/cards/love_3.jpg",
      "/cards/love_4.jpg",
      "/cards/love_5.jpg",
    ],
  },
  {
    name: "Thanks",
    cards: [
      "/cards/thanks_1.jpg",
      "/cards/thanks_2.jpg",
      "/cards/thanks_3.jpg",
      "/cards/thanks_4.jpg",
      "/cards/thanks_5.jpg",
      "/cards/thanks_6.jpg",
    ],
  },
  {
    name: "Featured",
    cards: [
      "/cards/featured_1.jpg",
      "/cards/featured_2.jpg",
      "/cards/featured_3.jpg",
      "/main.png",
      "/cards/featured_4.jpg",
      "/cards/featured_5.jpg",
      "/cards/featured_6.jpg",
      "/cards/featured_7.jpg",
    ],
  },
];

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Giftly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HStack className={styles.bannerContainer}>
          <VStack className={styles.bannerLeftSection}>
            <Text className={styles.bannerTitle}>
              Send a gift card to express your love and gratitude to someone
              <span className={styles.specialWord}> special</span> today.
            </Text>
            <Text className={styles.bannerSubtitle}>
              The perfect gift, for every occasion.
            </Text>
            <HStack>
              <Link href="/create">
                <Button className={styles.bannerSendButton}>Send Gift</Button>
              </Link>
              <Link href="/explore">
                <Button className={styles.bannerExploreButton}>Explore </Button>
              </Link>
            </HStack>
          </VStack>
          <VStack className={styles.bannerRightSection}>
            <Image
              src="/main.png"
              alt="Banner gift card"
              className={styles.bannerCard}
            />
          </VStack>
        </HStack>
        <Box h="5rem"></Box>
        {sampleCardCategories.map(({ name, cards }, idx) => (
          <VStack key={idx} className={styles.cardCategoryContainer}>
            <HStack className={styles.cardCategoryHeaderContainer}>
              <Text className={styles.cardCategoryHeaderTitle}>{name}</Text>
              <Text className={styles.cardCategoryHeaderSubtitle}>See all</Text>
            </HStack>
            <HStack className={styles.cardCategoryCarouselContainer}>
              {cards.map((image, index) => (
                <Link key={index} href="/create">
                  <Image
                    src={image}
                    cursor="pointer"
                    alt="Card"
                    className={styles.cardCategoryCarouselImage}
                  />
                </Link>
              ))}
            </HStack>
          </VStack>
        ))}
      </main>
      <Footer />
    </div>
  );
};

export default withTransition(Home);
